spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: product_user
    password: product_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}